### ISSUE TITLE
"Visual Studio Code" can't be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by mikelehen** [gantsign/ansible-role-visual-studio-code#169]
macOS Catalina
Installed via cask.

While gantsign.visual-studio-code successfully installs VS Code (via cask), it fails to install extensions because macOS pops up this dialog (repeatedly):
![image](https://user-images.githubusercontent.com/206364/73810643-f5e9fc00-478b-11ea-9a79-19137ea3e21d.png)

If you click "Show in Finder", right click Visual Studio Code and choose "Open" then you get the same dialog but with an extra button to "Open". Once you've opened VS Code once, then you can re-run the role and it will work as expected.

**Comment by freemanjp** [comment]
@mikelehen thanks for reporting this issue.

The macOS support was contributed by a user in #141. Unfortunately, since I don't own a mac and the [Molecule](https://molecule.readthedocs.io/en/latest/) test framework for Ansible doesn't support macOS, I've no way of maintaining this feature myself. I accepted the change as an undocumented/unsupported feature.

I'm happy to accept a PR if you have a solution for this issue, but I'm unable to develop/test a solution myself.

**Comment by mikelehen** [comment]
Thanks for the reply! Yeah, I figured that might be the case.

Doing a bit more digging, I think this may actually be a VS Code issue that has just been fixed (for insider builds). https://github.com/microsoft/vscode/issues/74782

I'll go ahead and optimistically close this.  If I or somebody else runs into it again down the road, it can be re-opened.  Thanks!
